if(NOT DEFINED COMPILER OR NOT DEFINED FIXTURES OR NOT DEFINED WORK)
  message(FATAL_ERROR "COMPILER, FIXTURES, and WORK are required")
endif()

file(MAKE_DIRECTORY "${WORK}")
set(output "${WORK}/generated.hpp")
set(ir_output "${WORK}/pipeline.ffir.json")
set(reordered_output "${WORK}/generated-reordered.hpp")
set(other_cwd "${WORK}/other-cwd")
file(MAKE_DIRECTORY "${other_cwd}")
file(WRITE "${output}" "preserve-generated-output\n")
file(WRITE "${ir_output}" "preserve-ir-output\n")

execute_process(
  COMMAND
    "${COMPILER}" compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
  RESULT_VARIABLE result
  OUTPUT_VARIABLE stdout
  ERROR_VARIABLE stderr
)
if(NOT result EQUAL 0 OR NOT stdout STREQUAL "" OR NOT stderr STREQUAL "")
  message(FATAL_ERROR "compile failed or produced console output: ${result}: ${stdout}${stderr}")
endif()
file(READ "${output}" output_after)
if(NOT output_after MATCHES "^// Generated by FeedForge compiler ")
  message(FATAL_ERROR "compile did not emit a generated C++ header")
endif()
file(SHA256 "${output}" first_hash)

execute_process(
  COMMAND
    "${COMPILER}" dump-ir
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${ir_output}"
  RESULT_VARIABLE dump_result
  OUTPUT_VARIABLE dump_stdout
  ERROR_VARIABLE dump_stderr
)
if(NOT dump_result EQUAL 0 OR NOT dump_stdout STREQUAL "" OR
   NOT dump_stderr STREQUAL "")
  message(FATAL_ERROR "dump-ir failed or produced console output: ${dump_result}: ${dump_stdout}${dump_stderr}")
endif()
file(READ "${ir_output}" ir_after)
if(NOT ir_after MATCHES "^\\{\"format_version\":1,")
  message(FATAL_ERROR "dump-ir did not emit canonical FFIR JSON")
endif()

execute_process(
  COMMAND
    "${COMPILER}" compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
  WORKING_DIRECTORY "${other_cwd}"
  RESULT_VARIABLE repeat_result
  ERROR_VARIABLE repeat_stderr
)
if(NOT repeat_result EQUAL 0 OR NOT repeat_stderr STREQUAL "")
  message(FATAL_ERROR "repeat cross-directory emission failed: ${repeat_stderr}")
endif()
file(SHA256 "${output}" repeat_hash)
if(NOT first_hash STREQUAL repeat_hash)
  message(FATAL_ERROR "repeat cross-directory output was not byte-identical")
endif()

execute_process(
  COMMAND
    "${COMPILER}" compile
    --schema "${FIXTURES}/valid_schema_reordered.toml"
    --pipeline "${FIXTURES}/valid_pipeline_reordered.toml"
    --output "${reordered_output}"
  WORKING_DIRECTORY "${other_cwd}"
  RESULT_VARIABLE reordered_result
  ERROR_VARIABLE reordered_stderr
)
if(NOT reordered_result EQUAL 0 OR NOT reordered_stderr STREQUAL "")
  message(FATAL_ERROR "semantic-reordering emission failed: ${reordered_stderr}")
endif()
file(SHA256 "${reordered_output}" reordered_hash)
if(NOT first_hash STREQUAL reordered_hash)
  message(FATAL_ERROR "semantic TOML reordering changed generated output")
endif()
string(FIND "${output_after}" "${FIXTURES}" fixture_path_position)
string(FIND "${output_after}" "${WORK}" work_path_position)
if(NOT fixture_path_position EQUAL -1 OR NOT work_path_position EQUAL -1)
  message(FATAL_ERROR "generated source contains an absolute source/output path")
endif()
if(output_after MATCHES "Generated at|Generated on|generation time|hostname|username")
  message(FATAL_ERROR "generated source contains unstable host/time provenance")
endif()

file(WRITE "${output}" "preserve-removed-option\n")
execute_process(
  COMMAND
    "${COMPILER}" compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
    --dump-ir "${ir_output}"
  RESULT_VARIABLE removed_option_result
  ERROR_VARIABLE removed_option_stderr
)
if(NOT removed_option_result EQUAL 2 OR
   NOT removed_option_stderr MATCHES "FFCLI001")
  message(FATAL_ERROR "removed --dump-ir option was not rejected")
endif()
file(READ "${output}" removed_option_after)
if(NOT removed_option_after STREQUAL "preserve-removed-option\n")
  message(FATAL_ERROR "rejected --dump-ir option modified --output")
endif()

file(WRITE "${output}" "preserve-invalid-output\n")
execute_process(
  COMMAND
    "${COMPILER}" compile
    --schema "${FIXTURES}/invalid_schema_unknown_key.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
  RESULT_VARIABLE invalid_result
  ERROR_VARIABLE invalid_stderr
)
if(NOT invalid_result EQUAL 2 OR NOT invalid_stderr MATCHES "^FFSCHEMA002 ")
  message(FATAL_ERROR "invalid input did not return its stable diagnostic")
endif()
file(READ "${output}" invalid_output_after)
if(NOT invalid_output_after STREQUAL "preserve-invalid-output\n")
  message(FATAL_ERROR "invalid input modified --output")
endif()

set(alias_schema "${WORK}/alias-schema.toml")
file(COPY_FILE "${FIXTURES}/valid_schema.toml" "${alias_schema}")
file(READ "${alias_schema}" alias_schema_before)
execute_process(
  COMMAND
    "${COMPILER}" dump-ir
    --schema "${alias_schema}"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${alias_schema}"
  RESULT_VARIABLE source_alias_result
  ERROR_VARIABLE source_alias_stderr
)
if(NOT source_alias_result EQUAL 2 OR NOT source_alias_stderr MATCHES "^FFCLI002 ")
  message(FATAL_ERROR "source/output alias was not rejected safely")
endif()
file(READ "${alias_schema}" alias_schema_after)
if(NOT alias_schema_after STREQUAL alias_schema_before)
  message(FATAL_ERROR "source/output alias modified the schema")
endif()

execute_process(
  COMMAND "${COMPILER}" validate --schema "${WORK}/missing-schema.toml"
  RESULT_VARIABLE missing_input_result
  ERROR_VARIABLE missing_input_stderr
)
if(NOT missing_input_result EQUAL 3 OR NOT missing_input_stderr MATCHES "^FFIO001 ")
  message(FATAL_ERROR "input I/O failure did not use exit 3 and FFIO001")
endif()

string(REPEAT "x" 1048577 oversized_source)
file(WRITE "${WORK}/oversized-schema.toml" "${oversized_source}")
execute_process(
  COMMAND "${COMPILER}" validate --schema "${WORK}/oversized-schema.toml"
  RESULT_VARIABLE oversized_result
  ERROR_VARIABLE oversized_stderr
)
if(NOT oversized_result EQUAL 2 OR
   NOT oversized_stderr MATCHES "^FFLIMIT001 ")
  message(FATAL_ERROR "oversized input did not use exit 2 and FFLIMIT001")
endif()

execute_process(
  COMMAND "${COMPILER}" validate
  RESULT_VARIABLE usage_result
  ERROR_VARIABLE usage_stderr
)
if(NOT usage_result EQUAL 2 OR NOT usage_stderr MATCHES "FFCLI001")
  message(FATAL_ERROR "invalid CLI did not use exit 2 and FFCLI001")
endif()

file(REMOVE_RECURSE "${WORK}/missing-parent")
foreach(action IN ITEMS compile dump-ir)
  execute_process(
    COMMAND
      "${COMPILER}" "${action}"
      --schema "${FIXTURES}/valid_schema.toml"
      --pipeline "${FIXTURES}/valid_pipeline.toml"
      --output "${WORK}/missing-parent/output"
    RESULT_VARIABLE missing_parent_result
    ERROR_VARIABLE missing_parent_stderr
  )
  if(NOT missing_parent_result EQUAL 3 OR
     NOT missing_parent_stderr MATCHES "^FFIO002 ")
    message(FATAL_ERROR "${action} output failure did not use exit 3 and FFIO002")
  endif()
endforeach()

set(replace_directory "${WORK}/replace-directory")
file(REMOVE_RECURSE "${replace_directory}")
file(MAKE_DIRECTORY "${replace_directory}")
file(WRITE "${replace_directory}/sentinel" "preserve-directory\n")
execute_process(
  COMMAND
    "${COMPILER}" compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${replace_directory}"
  RESULT_VARIABLE replace_directory_result
  ERROR_VARIABLE replace_directory_stderr
)
if(NOT replace_directory_result EQUAL 3 OR
   NOT replace_directory_stderr MATCHES "^FFIO002 ")
  message(FATAL_ERROR "failed atomic replacement did not use exit 3 and FFIO002")
endif()
file(READ "${replace_directory}/sentinel" sentinel_after)
if(NOT sentinel_after STREQUAL "preserve-directory\n")
  message(FATAL_ERROR "failed atomic replacement modified its destination")
endif()

file(GLOB_RECURSE leftovers "${WORK}/*.feedforgec.tmp.*")
if(leftovers)
  message(FATAL_ERROR "temporary output files remained: ${leftovers}")
endif()
