if(NOT DEFINED COMPILER OR NOT DEFINED FIXTURES OR NOT DEFINED WORK)
  message(FATAL_ERROR "COMPILER, FIXTURES, and WORK are required")
endif()

file(MAKE_DIRECTORY "${WORK}")
set(output "${WORK}/generated.hpp")
set(ir_output "${WORK}/pipeline.ffir.json")
set(reordered_output "${WORK}/generated-reordered.hpp")
set(other_cwd "${WORK}/other-cwd")
file(MAKE_DIRECTORY "${other_cwd}")
file(WRITE "${output}" "preserve-generated-output\n")
file(WRITE "${ir_output}" "old-ir\n")

execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
    --dump-ir "${ir_output}"
  RESULT_VARIABLE result
  OUTPUT_VARIABLE stdout
  ERROR_VARIABLE stderr
)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "expected successful emission, got ${result}: ${stderr}")
endif()
if(NOT stdout STREQUAL "")
  message(FATAL_ERROR "compile wrote unexpected standard output: ${stdout}")
endif()
if(NOT stderr STREQUAL "")
  message(FATAL_ERROR "compile wrote unexpected standard error: ${stderr}")
endif()
file(READ "${output}" output_after)
if(NOT output_after MATCHES "^// Generated by FeedForge compiler ")
  message(FATAL_ERROR "compile did not emit a generated C++ header")
endif()
file(READ "${ir_output}" ir_after)
if(NOT ir_after MATCHES "^\\{\"format_version\":1,")
  message(FATAL_ERROR "--dump-ir did not receive canonical FFIR JSON")
endif()
file(SHA256 "${output}" first_hash)

execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
    --dump-ir "${ir_output}"
  WORKING_DIRECTORY "${other_cwd}"
  RESULT_VARIABLE repeat_result
  ERROR_VARIABLE repeat_stderr
)
if(NOT repeat_result EQUAL 0 OR NOT repeat_stderr STREQUAL "")
  message(FATAL_ERROR "repeat cross-directory emission failed: ${repeat_stderr}")
endif()
file(SHA256 "${output}" repeat_hash)
if(NOT first_hash STREQUAL repeat_hash)
  message(FATAL_ERROR "repeat cross-directory output was not byte-identical")
endif()

execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/valid_schema_reordered.toml"
    --pipeline "${FIXTURES}/valid_pipeline_reordered.toml"
    --output "${reordered_output}"
  WORKING_DIRECTORY "${other_cwd}"
  RESULT_VARIABLE reordered_result
  ERROR_VARIABLE reordered_stderr
)
if(NOT reordered_result EQUAL 0 OR NOT reordered_stderr STREQUAL "")
  message(FATAL_ERROR "semantic-reordering emission failed: ${reordered_stderr}")
endif()
file(SHA256 "${reordered_output}" reordered_hash)
if(NOT first_hash STREQUAL reordered_hash)
  message(FATAL_ERROR "semantic TOML reordering changed generated output")
endif()
string(FIND "${output_after}" "${FIXTURES}" fixture_path_position)
string(FIND "${output_after}" "${WORK}" work_path_position)
if(NOT fixture_path_position EQUAL -1 OR NOT work_path_position EQUAL -1)
  message(FATAL_ERROR "generated source contains an absolute source/output path")
endif()
if(output_after MATCHES
   "Generated at|Generated on|generation time|hostname|username")
  message(FATAL_ERROR "generated source contains unstable host/time provenance")
endif()

execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
    --dump-ir "${output}"
  RESULT_VARIABLE alias_result
  ERROR_VARIABLE alias_stderr
)
if(NOT alias_result EQUAL 2 OR NOT alias_stderr MATCHES "^FFCLI002 ")
  message(FATAL_ERROR "aliased output paths were not rejected safely")
endif()
file(READ "${output}" alias_output_after)
if(NOT alias_output_after STREQUAL output_after)
  message(FATAL_ERROR "aliased --dump-ir modified --output")
endif()

file(WRITE "${output}" "preserve-invalid-output\n")
file(WRITE "${ir_output}" "preserve-invalid-ir\n")
execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/invalid_schema_unknown_key.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
    --dump-ir "${ir_output}"
  RESULT_VARIABLE invalid_result
  ERROR_VARIABLE invalid_stderr
)
if(NOT invalid_result EQUAL 2)
  message(FATAL_ERROR "expected invalid-input exit 2, got ${invalid_result}")
endif()
if(NOT invalid_stderr MATCHES "^FFSCHEMA002 ")
  message(FATAL_ERROR "missing stable schema diagnostic: ${invalid_stderr}")
endif()
file(READ "${output}" invalid_output_after)
file(READ "${ir_output}" invalid_ir_after)
if(NOT invalid_output_after STREQUAL "preserve-invalid-output\n")
  message(FATAL_ERROR "invalid input modified --output")
endif()
if(NOT invalid_ir_after STREQUAL "preserve-invalid-ir\n")
  message(FATAL_ERROR "invalid input modified --dump-ir")
endif()

set(alias_schema "${WORK}/alias-schema.toml")
file(COPY_FILE "${FIXTURES}/valid_schema.toml" "${alias_schema}")
file(READ "${alias_schema}" alias_schema_before)
execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${alias_schema}"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${alias_schema}"
  RESULT_VARIABLE source_alias_result
  ERROR_VARIABLE source_alias_stderr
)
if(NOT source_alias_result EQUAL 2 OR
   NOT source_alias_stderr MATCHES "^FFCLI002 ")
  message(FATAL_ERROR "source/output alias was not rejected safely")
endif()
file(READ "${alias_schema}" alias_schema_after)
if(NOT alias_schema_after STREQUAL alias_schema_before)
  message(FATAL_ERROR "source/output alias modified the schema")
endif()

execute_process(
  COMMAND "${COMPILER}" validate --schema "${WORK}/missing-schema.toml"
  RESULT_VARIABLE missing_input_result
  ERROR_VARIABLE missing_input_stderr
)
if(NOT missing_input_result EQUAL 3 OR
   NOT missing_input_stderr MATCHES "^FFIO001 ")
  message(FATAL_ERROR "input I/O failure did not use exit 3 and FFIO001")
endif()

execute_process(
  COMMAND "${COMPILER}" validate
  RESULT_VARIABLE usage_result
  ERROR_VARIABLE usage_stderr
)
if(NOT usage_result EQUAL 2 OR NOT usage_stderr MATCHES "FFCLI001")
  message(FATAL_ERROR "invalid CLI did not use exit 2 and FFCLI001")
endif()

file(REMOVE_RECURSE "${WORK}/missing-parent")
file(WRITE "${ir_output}" "preserve-parent-failure-ir\n")
execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${WORK}/missing-parent/generated.hpp"
    --dump-ir "${ir_output}"
  RESULT_VARIABLE missing_parent_result
  ERROR_VARIABLE missing_parent_stderr
)
if(NOT missing_parent_result EQUAL 3 OR
   NOT missing_parent_stderr MATCHES "^FFIO002 ")
  message(FATAL_ERROR "output I/O failure did not use exit 3 and FFIO002")
endif()
file(READ "${ir_output}" parent_failure_ir_after)
if(NOT parent_failure_ir_after STREQUAL "preserve-parent-failure-ir\n")
  message(FATAL_ERROR "missing output parent modified --dump-ir")
endif()

file(WRITE "${output}" "preserve-dump-parent-output\n")
execute_process(
  COMMAND
    "${COMPILER}"
    compile
    --schema "${FIXTURES}/valid_schema.toml"
    --pipeline "${FIXTURES}/valid_pipeline.toml"
    --output "${output}"
    --dump-ir "${WORK}/missing-parent/pipeline.ffir.json"
  RESULT_VARIABLE missing_dump_parent_result
  ERROR_VARIABLE missing_dump_parent_stderr
)
if(NOT missing_dump_parent_result EQUAL 3 OR
   NOT missing_dump_parent_stderr MATCHES "^FFIO002 ")
  message(FATAL_ERROR "dump I/O failure did not use exit 3 and FFIO002")
endif()
file(READ "${output}" dump_parent_output_after)
if(NOT dump_parent_output_after STREQUAL "preserve-dump-parent-output\n")
  message(FATAL_ERROR "missing dump parent modified --output")
endif()

file(GLOB_RECURSE leftovers "${WORK}/*.feedforgec.tmp.*")
if(leftovers)
  message(FATAL_ERROR "temporary output files remained: ${leftovers}")
endif()
