// Generated by FeedForge compiler 0.2.0.
// DO NOT EDIT.
// FFIR format version: 1
// Schema: test_feed (protocol 1.0, document revision 2026-07-14)
// Schema fingerprint: b73bec7da412b8e0324f15750f7b4e91ea1552060e8fea1712ccb8d915493872
// Pipeline: test_projection
// Pipeline fingerprint: eff76565a963f1bb661180ecf05d3b3256758c3a1fd3bb6754a4998dcf91a87a
// Profile/variant: portable_checked/portable_checked.v1

#ifndef FEEDFORGE_GENERATED_B73BEC7DA412B8E0324F15750F7B4E91EA1552060E8FEA1712CCB8D915493872_EFF76565A963F1BB661180ECF05D3B3256758C3A1FD3BB6754A4998DCF91A87A_HPP
#define FEEDFORGE_GENERATED_B73BEC7DA412B8E0324F15750F7B4E91EA1552060E8FEA1712CCB8D915493872_EFF76565A963F1BB661180ECF05D3B3256758C3A1FD3BB6754A4998DCF91A87A_HPP

#include <array>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <span>
#include <string_view>
#include <type_traits>

#include <feedforge/flow.hpp>
#include <feedforge/framing/binary_file.hpp>
#include <feedforge/profile/concepts.hpp>
#include <feedforge/profile/portable_checked.hpp>
#include <feedforge/result.hpp>
#include <feedforge/types/ascii.hpp>
#include <feedforge/types/decimal.hpp>
#include <feedforge/types/identifiers.hpp>
#include <feedforge/types/timestamp.hpp>
#include <feedforge/version.hpp>
#include <feedforge/wire/load_big_endian.hpp>

namespace feedforge::generated::test_projection {

struct pipeline_metadata {
  struct known_message {
    std::byte discriminator{};
    std::uint16_t size{};
  };

  static constexpr std::uint32_t required_runtime_api_version{2U};
  static constexpr std::uint32_t ffir_format_version{1U};
  static constexpr std::string_view generator_version{"0.2.0"};
  static constexpr std::string_view schema_fingerprint{"b73bec7da412b8e0324f15750f7b4e91ea1552060e8fea1712ccb8d915493872"};
  static constexpr std::string_view pipeline_fingerprint{"eff76565a963f1bb661180ecf05d3b3256758c3a1fd3bb6754a4998dcf91a87a"};
  static constexpr std::string_view profile_name{"portable_checked"};
  static constexpr std::string_view profile_variant_id{"portable_checked.v1"};
  static constexpr std::array<known_message, 3U> known_messages{{
    {std::byte{0x41U}, std::uint16_t{9U}},
    {std::byte{0x48U}, std::uint16_t{2U}},
    {std::byte{0x55U}, std::uint16_t{4U}},
  }};
};

static_assert(feedforge::runtime_api_version ==
    pipeline_metadata::required_runtime_api_version,
    "FeedForge runtime API mismatch; regenerate this header with a compatible compiler");
static_assert(feedforge::decoder_implementation<
    feedforge::profile::portable_checked>,
    "portable_checked must satisfy decoder_implementation");
static_assert(feedforge::profile::portable_checked::variant_id ==
    pipeline_metadata::profile_variant_id,
    "generated profile variant does not match the runtime profile");

static_assert(pipeline_metadata::known_messages.size() == 3U, "known message table size changed");
static_assert(pipeline_metadata::known_messages[0U].discriminator == std::byte{0x41U}, "known message discriminator changed");
static_assert(pipeline_metadata::known_messages[0U].size == std::uint16_t{9U}, "known message size changed");
static_assert(pipeline_metadata::known_messages[1U].discriminator == std::byte{0x48U}, "known message discriminator changed");
static_assert(pipeline_metadata::known_messages[1U].size == std::uint16_t{2U}, "known message size changed");
static_assert(pipeline_metadata::known_messages[2U].discriminator == std::byte{0x55U}, "known message discriminator changed");
static_assert(pipeline_metadata::known_messages[2U].size == std::uint16_t{4U}, "known message size changed");
static_assert(pipeline_metadata::known_messages[0U].discriminator != pipeline_metadata::known_messages[1U].discriminator, "known message discriminators must be unique");
static_assert(pipeline_metadata::known_messages[0U].discriminator != pipeline_metadata::known_messages[2U].discriminator, "known message discriminators must be unique");
static_assert(pipeline_metadata::known_messages[1U].discriminator != pipeline_metadata::known_messages[2U].discriminator, "known message discriminators must be unique");

struct add_order {
  feedforge::decimal<std::uint32_t, 4> price{};
  feedforge::ascii<1U> side{};

  static constexpr std::byte source_discriminator{0x41U};
  static constexpr std::string_view event_name{"add_order"};

  friend constexpr bool operator==(const add_order&, const add_order&) = default;
};

static_assert(std::is_default_constructible_v<add_order>);
static_assert(std::is_aggregate_v<add_order>);
static_assert(std::is_standard_layout_v<add_order>);
static_assert(std::is_trivially_copyable_v<add_order>);
static_assert(std::same_as<decltype(add_order::price), feedforge::decimal<std::uint32_t, 4>>, "projected field type changed");
static_assert(3U + 4U <= pipeline_metadata::known_messages[0U].size, "projected field exceeds message bounds");
static_assert(feedforge::wire::supported_unsigned_width<4U>, "projected unsigned width is unsupported");
static_assert((4U == 4U || 4U == 8U) && 4U <= 18U, "projected decimal width or scale is unsupported");
static_assert(std::same_as<decltype(add_order::side), feedforge::ascii<1U>>, "projected field type changed");
static_assert(7U + 1U <= pipeline_metadata::known_messages[0U].size, "projected field exceeds message bounds");
static_assert(1U > 0U, "projected ASCII width must be positive");

struct order_update {
  std::uint16_t quantity{};
  feedforge::ascii<1U> code{};

  static constexpr std::byte source_discriminator{0x55U};
  static constexpr std::string_view event_name{"order_update"};

  friend constexpr bool operator==(const order_update&, const order_update&) = default;
};

static_assert(std::is_default_constructible_v<order_update>);
static_assert(std::is_aggregate_v<order_update>);
static_assert(std::is_standard_layout_v<order_update>);
static_assert(std::is_trivially_copyable_v<order_update>);
static_assert(std::same_as<decltype(order_update::quantity), std::uint16_t>, "projected field type changed");
static_assert(1U + 2U <= pipeline_metadata::known_messages[2U].size, "projected field exceeds message bounds");
static_assert(feedforge::wire::supported_unsigned_width<2U>, "projected unsigned width is unsupported");
static_assert(std::same_as<decltype(order_update::code), feedforge::ascii<1U>>, "projected field type changed");
static_assert(3U + 1U <= pipeline_metadata::known_messages[2U].size, "projected field exceeds message bounds");
static_assert(1U > 0U, "projected ASCII width must be positive");

static_assert(add_order::source_discriminator != order_update::source_discriminator, "selected event discriminators must be unique");
static_assert(add_order::event_name != order_update::event_name, "selected event names must be unique");

template <class Sink>
concept sink_for_all_selected_events =
    feedforge::sink_for<Sink, add_order> &&
    feedforge::sink_for<Sink, order_update>;

template <feedforge::decoder_implementation Implementation>
class basic_decoder {
 public:
  template <class Sink>
    requires sink_for_all_selected_events<Sink>
  [[nodiscard]] FEEDFORGE_FORCE_INLINE feedforge::decode_outcome decode_one(
      std::span<const std::byte> payload, Sink& sink) const noexcept {
    const std::size_t actual_size = payload.size();
    if (payload.empty()) {
      return feedforge::decode_outcome{
        feedforge::decode_status::empty_payload,
        std::byte{0x00U},
        std::uint16_t{0U},
        actual_size,
      };
    }

    const std::byte message_type = payload[0U];
    const std::uint8_t discriminator = std::to_integer<std::uint8_t>(message_type);
    switch (discriminator) {
      case 0x41U: {
        constexpr std::uint16_t expected_size{9U};
        if (actual_size != static_cast<std::size_t>(expected_size)) {
          return feedforge::decode_outcome{
            feedforge::decode_status::invalid_message_size,
            message_type,
            expected_size,
            actual_size,
          };
        }
        add_order event{};
        event.price = feedforge::decimal<std::uint32_t, 4>{static_cast<std::uint32_t>(Implementation::template load_unsigned<4U>(payload.data() + 3U))};
        std::memcpy(event.side.raw.data(), payload.data() + 7U, 1U);
        if (sink(event) == feedforge::flow::stop) {
          return feedforge::decode_outcome{
            feedforge::decode_status::stopped,
            message_type,
            expected_size,
            actual_size,
          };
        }
        return feedforge::decode_outcome{
          feedforge::decode_status::emitted,
          message_type,
          expected_size,
          actual_size,
        };
      }
      case 0x55U: {
        constexpr std::uint16_t expected_size{4U};
        if (actual_size != static_cast<std::size_t>(expected_size)) {
          return feedforge::decode_outcome{
            feedforge::decode_status::invalid_message_size,
            message_type,
            expected_size,
            actual_size,
          };
        }
        order_update event{};
        event.quantity = static_cast<std::uint16_t>(Implementation::template load_unsigned<2U>(payload.data() + 1U));
        std::memcpy(event.code.raw.data(), payload.data() + 3U, 1U);
        if (sink(event) == feedforge::flow::stop) {
          return feedforge::decode_outcome{
            feedforge::decode_status::stopped,
            message_type,
            expected_size,
            actual_size,
          };
        }
        return feedforge::decode_outcome{
          feedforge::decode_status::emitted,
          message_type,
          expected_size,
          actual_size,
        };
      }
      default:
        break;
    }

    std::uint16_t expected_size{};
    switch (discriminator) {
      case 0x48U:
        expected_size = std::uint16_t{2U};
        break;
      default:
        return feedforge::decode_outcome{
          feedforge::decode_status::unknown_message_type,
          message_type,
          std::uint16_t{0U},
          actual_size,
        };
    }

    if (actual_size != static_cast<std::size_t>(expected_size)) {
      return feedforge::decode_outcome{
        feedforge::decode_status::invalid_message_size,
        message_type,
        expected_size,
        actual_size,
      };
    }

    return feedforge::decode_outcome{
      feedforge::decode_status::known_unselected_skipped,
      message_type,
      expected_size,
      actual_size,
    };
  }
};

using decoder = basic_decoder<feedforge::profile::portable_checked>;

template <class Sink>
  requires sink_for_all_selected_events<Sink>
[[nodiscard]] feedforge::replay_summary replay_binary_file(
    std::span<const std::byte> input, Sink& sink) noexcept {
  decoder message_decoder{};
  feedforge::replay_summary summary{};
  std::size_t position{};

  for (;;) {
    const std::size_t available = input.size() - position;
    if (available == 0U) {
      summary.status = feedforge::replay_status::incomplete;
      summary.bytes_consumed = position;
      return summary;
    }
    if (available == 1U) {
      summary.status = feedforge::replay_status::framing_error;
      summary.bytes_consumed = position;
      summary.error_offset = position;
      summary.framing_error = feedforge::framing_errc::truncated_length_prefix;
      return summary;
    }

    const std::size_t frame_offset = position;
    const auto high = std::to_integer<std::uint16_t>(input[position]);
    const auto low = std::to_integer<std::uint16_t>(input[position + 1U]);
    const auto payload_size = static_cast<std::uint16_t>((high << 8U) | low);

    if (payload_size == 0U) {
      position += 2U;
      if (position != input.size()) {
        summary.status = feedforge::replay_status::framing_error;
        summary.bytes_consumed = position;
        summary.error_offset = position;
        summary.framing_error = feedforge::framing_errc::trailing_data_after_end_marker;
        return summary;
      }
      summary.status = feedforge::replay_status::complete;
      summary.bytes_consumed = position;
      return summary;
    }

    if (static_cast<std::size_t>(payload_size) > available - 2U) {
      summary.status = feedforge::replay_status::framing_error;
      summary.bytes_consumed = position;
      summary.error_offset = frame_offset;
      summary.framing_error = feedforge::framing_errc::truncated_payload;
      return summary;
    }

    const auto payload = input.subspan(position + 2U, payload_size);
    position += 2U + static_cast<std::size_t>(payload_size);
    ++summary.frames_seen;
    const feedforge::decode_outcome outcome = message_decoder.decode_one(payload, sink);
    if (outcome.status == feedforge::decode_status::emitted) {
      ++summary.events_emitted;
      continue;
    }
    if (outcome.status == feedforge::decode_status::known_unselected_skipped) {
      ++summary.known_messages_skipped;
      continue;
    }
    if (outcome.status == feedforge::decode_status::unknown_skipped) {
      ++summary.unknown_messages_skipped;
      continue;
    }
    if (outcome.status == feedforge::decode_status::stopped) {
      ++summary.events_emitted;
      summary.status = feedforge::replay_status::stopped;
      summary.bytes_consumed = position;
      return summary;
    }
    summary.status = feedforge::replay_status::decode_error;
    summary.bytes_consumed = position;
    summary.error_offset = frame_offset + 2U;
    summary.decode_error = outcome;
    return summary;
  }
}

template <class Sink>
  requires sink_for_all_selected_events<Sink>
class chunked_replayer {
 public:
  explicit chunked_replayer(
      std::span<std::byte> scratch, Sink& sink) noexcept
    : cursor_(scratch), sink_(sink) {
    summary_.status = feedforge::replay_status::incomplete;
  }

  chunked_replayer(const chunked_replayer&) = delete;
  chunked_replayer& operator=(const chunked_replayer&) = delete;
  chunked_replayer(chunked_replayer&&) = delete;
  chunked_replayer& operator=(chunked_replayer&&) = delete;

  [[nodiscard]] feedforge::replay_summary push(
      std::span<const std::byte> chunk) noexcept {
    if (terminal_) {
      return summary_;
    }

    std::size_t position{};
    while (position != chunk.size()) {
      const feedforge::chunk_frame_outcome frame =
          cursor_.next(chunk.subspan(position));
      position += frame.input_consumed;
      summary_.bytes_consumed = cursor_.consumed();
      switch (frame.status) {
        case feedforge::chunk_frame_status::frame:
          if (!decode_frame(frame.frame)) {
            return summary_;
          }
          break;
        case feedforge::chunk_frame_status::needs_input:
          return summary_;
        case feedforge::chunk_frame_status::complete:
          summary_.status = feedforge::replay_status::complete;
          terminal_ = true;
          return summary_;
        case feedforge::chunk_frame_status::incomplete:
          summary_.status = feedforge::replay_status::incomplete;
          terminal_ = true;
          return summary_;
        case feedforge::chunk_frame_status::error:
          set_framing_error(frame);
          return summary_;
      }
    }
    return summary_;
  }

  [[nodiscard]] feedforge::replay_summary finish() noexcept {
    if (terminal_) {
      return summary_;
    }
    const feedforge::chunk_frame_outcome frame = cursor_.finish();
    summary_.bytes_consumed = cursor_.consumed();
    switch (frame.status) {
      case feedforge::chunk_frame_status::frame:
        static_cast<void>(decode_frame(frame.frame));
        return summary_;
      case feedforge::chunk_frame_status::needs_input:
        return summary_;
      case feedforge::chunk_frame_status::complete:
        summary_.status = feedforge::replay_status::complete;
        terminal_ = true;
        return summary_;
      case feedforge::chunk_frame_status::incomplete:
        summary_.status = feedforge::replay_status::incomplete;
        terminal_ = true;
        return summary_;
      case feedforge::chunk_frame_status::error:
        set_framing_error(frame);
        return summary_;
    }
    return summary_;
  }

  [[nodiscard]] feedforge::replay_summary summary() const noexcept {
    return summary_;
  }

 private:
  [[nodiscard]] bool decode_frame(
      const feedforge::frame_view& frame) noexcept {
    ++summary_.frames_seen;
    const feedforge::decode_outcome outcome =
        message_decoder_.decode_one(frame.payload, sink_);
    if (outcome.status == feedforge::decode_status::emitted) {
      ++summary_.events_emitted;
      return true;
    }
    if (outcome.status == feedforge::decode_status::known_unselected_skipped) {
      ++summary_.known_messages_skipped;
      return true;
    }
    if (outcome.status == feedforge::decode_status::unknown_skipped) {
      ++summary_.unknown_messages_skipped;
      return true;
    }
    if (outcome.status == feedforge::decode_status::stopped) {
      ++summary_.events_emitted;
      summary_.status = feedforge::replay_status::stopped;
    } else {
      summary_.status = feedforge::replay_status::decode_error;
      summary_.error_offset = static_cast<std::size_t>(frame.file_offset) + 2U;
      summary_.decode_error = outcome;
    }
    terminal_ = true;
    return false;
  }

  void set_framing_error(
      const feedforge::chunk_frame_outcome& frame) noexcept {
    summary_.status = feedforge::replay_status::framing_error;
    summary_.error_offset = static_cast<std::size_t>(frame.offset);
    summary_.framing_error = frame.error;
    terminal_ = true;
  }

  feedforge::chunked_binary_file_cursor cursor_;
  decoder message_decoder_{};
  Sink& sink_;
  feedforge::replay_summary summary_{};
  bool terminal_{};
};

}  // namespace feedforge::generated::test_projection

#endif  // FEEDFORGE_GENERATED_B73BEC7DA412B8E0324F15750F7B4E91EA1552060E8FEA1712CCB8D915493872_EFF76565A963F1BB661180ECF05D3B3256758C3A1FD3BB6754A4998DCF91A87A_HPP
